<?php

declare(strict_types=1);

require dirname(__DIR__,2).'/bootstrap.php';

use Trade\Config;
use Trade\Support\IranClock;
use Trade\Trading\NobitexPerformanceAnalytics;
use Trade\Updater;

if(!Config::installed()){header('Location:/install/');exit;}
session_name('trade_admin');session_set_cookie_params(['httponly'=>true,'secure'=>true,'samesite'=>'Strict','path'=>'/admin']);session_start();header('Cache-Control:no-store');
if(!isset($_SESSION['admin_id'])){header('Location:/admin/');exit;}
function h(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function f(mixed $v,int $d=2):string{return is_numeric($v)?number_format((float)$v,$d,'.',','):'—';}

$days=max(7,min(180,(int)($_GET['days']??30)));$error='';
try{$data=(new NobitexPerformanceAnalytics())->snapshot(null,$days);}catch(Throwable $e){$data=[];$error=mb_substr($e->getMessage(),0,800);}
if(($_GET['ajax']??'')==='1'){
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode(['ok'=>$error==='','data'=>$data,'error'=>$error,'time_iran'=>IranClock::nowPayload()],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);exit;
}
$summary=is_array($data['summary_by_quote']??null)?$data['summary_by_quote']:[];$irt=$summary['IRT']??[];$usdt=$summary['USDT']??[];$edge=$data['edge_calibration']??[];$assets=$data['asset_performance']??[];$daily=$data['daily_series_by_quote']['IRT']??[];$version=Updater::currentVersion();
require __DIR__.'/_nav.php';
?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>تحلیل عملکرد — Trade</title><link rel="stylesheet" href="/admin/assets/cockpit.css"><style>.bar-list{display:grid;gap:7px}.daybar{display:grid;grid-template-columns:90px 1fr 120px;gap:10px;align-items:center}.daybar i{display:block;height:8px;border-radius:999px;background:linear-gradient(90deg,#6246ea,#0891b2)}@media(max-width:600px){.daybar{grid-template-columns:78px 1fr 90px}}</style></head><body><div class="admin-shell">
<?php tradeAdminNav('analytics',$version);?>
<div class="page-head"><div><div class="page-eyebrow">PERFORMANCE / FEE AWARE / LIVE</div><h1>تحلیل عملکرد</h1><p>سود واقعی پس از کارمزد، Win Rate، Profit Factor، عملکرد دارایی‌ها و Expected Edge در برابر نتیجه واقعی؛ IRT در نمایش عمومی به تومان است.</p></div><span class="badge good"><span class="live-dot"></span>زنده • <?=$days?> روز</span></div>
<?php if($error!==''):?><div class="notice bad" id="analyticsError"><?=h($error)?></div><?php else:?><div class="notice bad" id="analyticsError" style="display:none"></div><?php endif?>
<form method="get" class="actions"><a class="btn <?=$days===7?'':'soft'?>" href="?days=7">۷ روز</a><a class="btn <?=$days===30?'':'soft'?>" href="?days=30">۳۰ روز</a><a class="btn <?=$days===90?'':'soft'?>" href="?days=90">۹۰ روز</a><span class="badge info" id="analyticsUpdated">آخرین بروزرسانی: <?=h($data['generated_at_iran']['jalali_datetime']??'—')?></span></form>
<div class="stat-grid" id="irtStats"><div class="stat-card"><span>PnL امروز</span><b class="<?=((float)($irt['today_net_pnl']??0)>=0)?'ok':'bad-text'?>"><?=f($irt['today_net_pnl']??0)?></b><small>تومان</small></div><div class="stat-card"><span>PnL هفته</span><b><?=f($irt['week_net_pnl']??0)?></b><small>تومان</small></div><div class="stat-card"><span>PnL ماه</span><b><?=f($irt['month_net_pnl']??0)?></b><small>تومان</small></div><div class="stat-card"><span>Win Rate</span><b><?=f($irt['win_rate_percent']??0,1)?>٪</b></div><div class="stat-card"><span>Profit Factor</span><b><?=f($irt['profit_factor']??0,2)?></b></div><div class="stat-card"><span>Avg Return</span><b><?=f($irt['average_return_percent']??0,3)?>٪</b></div><div class="stat-card"><span>Max Drawdown</span><b><?=f($irt['max_drawdown_absolute']??0,2)?></b><small>تومان</small></div><div class="stat-card"><span>Trades</span><b><?=h($irt['trades']??0)?></b></div></div>
<div class="panel-grid"><section class="panel"><div class="panel-head"><div><h2>USDT Performance</h2><p>بدون تبدیل مصنوعی PnL؛ ارقام Quote اصلی حفظ شده‌اند.</p></div></div><div class="metric-grid" id="usdtStats"><div class="metric"><span>Today</span><b><?=f($usdt['today_net_pnl']??0,4)?></b></div><div class="metric"><span>Week</span><b><?=f($usdt['week_net_pnl']??0,4)?></b></div><div class="metric"><span>Month</span><b><?=f($usdt['month_net_pnl']??0,4)?></b></div><div class="metric"><span>Win Rate</span><b><?=f($usdt['win_rate_percent']??0,1)?>٪</b></div><div class="metric"><span>Profit Factor</span><b><?=f($usdt['profit_factor']??0,2)?></b></div><div class="metric"><span>Trades</span><b><?=h($usdt['trades']??0)?></b></div></div></section><section class="panel soft"><div class="panel-head"><div><h2>Edge Calibration</h2><p>مقایسه Edge پیش‌بینی‌شده در ورود با Return واقعی بسته‌شده.</p></div><span class="badge info" id="edgeSamples"><?=h($edge['samples']??0)?> نمونه</span></div><div class="metric-grid" id="edgeStats"><div class="metric"><span>Expected Edge</span><b><?=f($edge['average_expected_edge_percent']??null,3)?>٪</b></div><div class="metric"><span>Realized Return</span><b><?=f($edge['average_realized_return_percent']??null,3)?>٪</b></div><div class="metric"><span>Directional Hit</span><b><?=f($edge['directional_hit_rate_percent']??null,1)?>٪</b></div></div></section></div>
<section class="panel"><div class="panel-head"><div><h2>عملکرد دارایی‌ها</h2><p>بر اساس Net PnL واقعی بازه انتخاب‌شده؛ IRT با واحد تومان.</p></div></div><div class="table-wrap"><table><thead><tr><th>Asset</th><th>Quote</th><th>Trades</th><th>Net PnL</th><th>Avg Return</th><th>Win Rate</th></tr></thead><tbody id="assetRows"><?php if($assets===[]):?><tr><td colspan="6" class="empty">هنوز معامله بسته‌شده کافی وجود ندارد.</td></tr><?php endif?><?php foreach($assets as $r):?><tr><td><b><?=h($r['asset']??'—')?></b></td><td><?=h(($r['display_unit']??$r['quote_asset']??'—')==='TOMAN'?'تومان':($r['display_unit']??$r['quote_asset']??'—'))?></td><td><?=h($r['trades']??0)?></td><td class="<?=((float)($r['net_pnl']??0)>=0)?'ok':'bad-text'?>"><?=f($r['net_pnl']??0,4)?></td><td><?=f($r['average_return_percent']??0,3)?>٪</td><td><?=f($r['win_rate_percent']??0,1)?>٪</td></tr><?php endforeach?></tbody></table></div></section>
<section class="panel"><div class="panel-head"><div><h2>جریان سود و زیان روزانه — تومان</h2><p>Net PnL روزانه بر اساس روز ایران و تقویم شمسی.</p></div></div><div class="bar-list" id="dailyBars"><?php $max=1.0;foreach($daily as $r)$max=max($max,abs((float)($r['net_pnl']??0)));foreach(array_slice($daily,-14) as $r):$width=min(100,(abs((float)($r['net_pnl']??0))/$max)*100);?><div class="daybar"><span><?=h($r['day']??'')?></span><div class="progress"><i style="width:<?=$width?>%"></i></div><b class="<?=((float)($r['net_pnl']??0)>=0)?'ok':'bad-text'?>"><?=f($r['net_pnl']??0,2)?></b></div><?php endforeach?></div></section>
<?php tradeAdminFooter($version);?></div><script>
const ANALYTICS_DAYS=<?=json_encode($days)?>;
function metricValues(container,values){const metrics=[...document.querySelectorAll(container+' .metric')];values.forEach((v,i)=>{if(metrics[i])TradeUI.setText(metrics[i].querySelector('b'),v);});}
function stat(label,value){const card=[...document.querySelectorAll('#irtStats .stat-card')].find(c=>(c.querySelector('span')?.textContent||'').trim()===label);if(card){const b=card.querySelector('b');TradeUI.setText(b,value);}}
function renderAnalytics(d){const s=d.summary_by_quote||{},irt=s.IRT||{},usdt=s.USDT||{},edge=d.edge_calibration||{};stat('PnL امروز',TradeUI.formatNumber(irt.today_net_pnl,2));stat('PnL هفته',TradeUI.formatNumber(irt.week_net_pnl,2));stat('PnL ماه',TradeUI.formatNumber(irt.month_net_pnl,2));stat('Win Rate',TradeUI.formatNumber(irt.win_rate_percent,1)+'٪');stat('Profit Factor',TradeUI.formatNumber(irt.profit_factor,2));stat('Avg Return',TradeUI.formatNumber(irt.average_return_percent,3)+'٪');stat('Max Drawdown',TradeUI.formatNumber(irt.max_drawdown_absolute,2));stat('Trades',TradeUI.formatNumber(irt.trades,0));metricValues('#usdtStats',[TradeUI.formatNumber(usdt.today_net_pnl,4),TradeUI.formatNumber(usdt.week_net_pnl,4),TradeUI.formatNumber(usdt.month_net_pnl,4),TradeUI.formatNumber(usdt.win_rate_percent,1)+'٪',TradeUI.formatNumber(usdt.profit_factor,2),TradeUI.formatNumber(usdt.trades,0)]);metricValues('#edgeStats',[TradeUI.formatNumber(edge.average_expected_edge_percent,3)+'٪',TradeUI.formatNumber(edge.average_realized_return_percent,3)+'٪',TradeUI.formatNumber(edge.directional_hit_rate_percent,1)+'٪']);TradeUI.setText('#edgeSamples',TradeUI.formatNumber(edge.samples??0,0)+' نمونه');TradeUI.setText('#analyticsUpdated','آخرین بروزرسانی: '+TradeUI.iranFromPayload(d.generated_at_iran));const assets=d.asset_performance||[];document.getElementById('assetRows').innerHTML=assets.length?assets.map(r=>`<tr><td><b>${TradeUI.escapeHtml(r.asset||'—')}</b></td><td>${TradeUI.escapeHtml(r.display_unit==='TOMAN'?'تومان':(r.display_unit||r.quote_asset||'—'))}</td><td>${TradeUI.formatNumber(r.trades,0)}</td><td class="${Number(r.net_pnl)>=0?'ok':'bad-text'}">${TradeUI.formatNumber(r.net_pnl,4)}</td><td>${TradeUI.formatNumber(r.average_return_percent,3)}٪</td><td>${TradeUI.formatNumber(r.win_rate_percent,1)}٪</td></tr>`).join(''):'<tr><td colspan="6" class="empty">هنوز معامله بسته‌شده کافی وجود ندارد.</td></tr>';const daily=(d.daily_series_by_quote?.IRT||[]).slice(-14),max=Math.max(1,...daily.map(r=>Math.abs(Number(r.net_pnl)||0)));document.getElementById('dailyBars').innerHTML=daily.map(r=>`<div class="daybar"><span>${TradeUI.escapeHtml(r.day||'')}</span><div class="progress"><i style="width:${Math.min(100,Math.abs(Number(r.net_pnl)||0)/max*100)}%"></i></div><b class="${Number(r.net_pnl)>=0?'ok':'bad-text'}">${TradeUI.formatNumber(r.net_pnl,2)}</b></div>`).join('');}
window.addEventListener('DOMContentLoaded',()=>TradeUI.poll(async()=>{try{const j=await TradeUI.json('/admin/analytics.php?ajax=1&days='+ANALYTICS_DAYS);document.getElementById('analyticsError').style.display='none';renderAnalytics(j.data);}catch(e){const el=document.getElementById('analyticsError');el.style.display='block';el.textContent='بروزرسانی زنده ناموفق: '+e.message;}},5000));
</script></body></html>