<?php

declare(strict_types=1);

require dirname(__DIR__,2).'/bootstrap.php';

use Trade\Config;
use Trade\Trading\TradeCommandCenter;
use Trade\Updater;

if(!Config::installed()){header('Location:/install/');exit;}
session_name('trade_admin');
session_set_cookie_params(['httponly'=>true,'secure'=>true,'samesite'=>'Strict','path'=>'/admin']);
session_start();
header('Cache-Control:no-store,no-cache,must-revalidate,max-age=0');
if(!isset($_SESSION['admin_id'])){header('Location:/admin/');exit;}
if(!isset($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(24));

function cc_h(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function cc_n(mixed $v,int $d=2):string{return number_format((float)$v,$d,'.',',');}
function cc_badge(string $value):string{$v=strtolower($value);return in_array($v,['live','ready','on','closed','normal','low'],true)?'good':(in_array($v,['critical','open','full_stop','high','missing','off'],true)?'bad':'info');}

$cc=new TradeCommandCenter();$notice='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    try{
        if(!hash_equals((string)$_SESSION['csrf'],(string)($_POST['csrf']??'')))throw new RuntimeException('درخواست نامعتبر است. صفحه را تازه‌سازی کن.');
        $action=(string)($_POST['action']??'');
        if($action==='emergency'){$r=$cc->setEmergencyMode((string)($_POST['mode']??''));$notice='حالت اضطراری روی '.cc_h($r['mode']??'').' تنظیم شد.';}
        elseif($action==='preset'){$r=$cc->applyPreset((string)($_POST['preset']??''));$notice='Preset '.cc_h($r['preset']??'').' اعمال شد.';}
        elseif($action==='rollback'){$r=$cc->rollback((int)($_POST['history_id']??0));$notice='تنظیمات به Snapshot #'.(int)($r['rolled_back_to']??0).' بازگردانده شد.';}
        elseif($action==='shadow'){$cc->setShadowMode(isset($_POST['enabled']));$notice='حالت Shadow بروزرسانی شد.';}
        elseif($action==='rules'){$cc->configureNotificationRules([
            'enabled'=>isset($_POST['enabled']),'min_priority'=>(string)($_POST['min_priority']??'warning'),
            'drawdown_percent'=>(float)($_POST['drawdown_percent']??2),'pnl_loss_percent'=>(float)($_POST['pnl_loss_percent']??2),
            'circuit_open'=>isset($_POST['circuit_open']),'api_failures'=>isset($_POST['api_failures']),'pending_watchdog'=>isset($_POST['pending_watchdog']),
        ]);$notice='قوانین هشدار ذخیره شد.';}
        elseif($action==='preview'){$preview=$cc->previewSettings($_POST);$notice='پیش‌نمایش ریسک محاسبه شد.';}
        elseif($action==='lab'){$lab=$cc->strategyLab($_POST);$notice='سناریوی Strategy Lab اجرا شد؛ هیچ سفارش واقعی ارسال نشد.';}
    }catch(Throwable $e){$error=$e->getMessage();}
}

$s=$cc->snapshot();$version=Updater::currentVersion();$headline=$s['headline'];$strip=$s['status_strip'];$positions=$s['positions'];$alerts=$s['alerts'];$decision=$s['decision_explainability'];$ranking=$s['opportunity_ranking'];$radar=$s['market_radar'];$perf=$s['performance'];$history=$cc->history(null,20);$rules=$s['notification_rules'];$shadow=$s['shadow'];$preview=$preview??null;$lab=$lab??null;
require __DIR__.'/_nav.php';
?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#111827"><title>مرکز فرمان — Trade</title><link rel="stylesheet" href="/admin/assets/cockpit.css"><style>
.cc-strip{display:flex;gap:7px;flex-wrap:wrap;margin:12px 0 0}.cc-tabs{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.cc-mini{padding:10px;border:1px solid var(--border,#e5e7eb);border-radius:14px;background:var(--panel,#fff)}.cc-mini b{display:block;font-size:18px}.cc-alert{border-right:4px solid #d97706}.cc-alert.critical{border-right-color:#dc2626}.cc-position{display:grid;grid-template-columns:1.2fr repeat(6,minmax(0,.8fr));gap:8px;align-items:center;padding:10px 0;border-bottom:1px solid #e5e7eb}.cc-heat{display:grid;gap:4px;min-width:520px}.cc-cell{padding:7px;border-radius:8px;text-align:center;font-size:11px}.cc-chart{height:150px;display:flex;align-items:flex-end;gap:3px;padding-top:8px}.cc-bar{min-width:5px;flex:1;background:#6556e8;border-radius:4px 4px 0 0;opacity:.85}.cc-actions{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.cc-actions form{margin:0}.cc-actions button{width:100%}.cc-danger{border:1px solid #fecaca;background:#fff7f7}.cc-radar{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.cc-radar section{border-radius:16px;padding:12px}.excellent{background:#ecfdf5}.goodradar{background:#eff6ff}.watch{background:#fffbeb}.avoid{background:#fef2f2}@media(max-width:900px){.cc-tabs,.cc-actions,.cc-radar{grid-template-columns:repeat(2,minmax(0,1fr))}.cc-position{grid-template-columns:1fr 1fr}.cc-position>*{min-width:0}}@media(max-width:480px){.cc-tabs,.cc-actions,.cc-radar{grid-template-columns:1fr}}
</style></head><body><div class="admin-shell"><?php tradeAdminNav('command',$version);?>
<div class="page-head"><div><div class="page-eyebrow">TRADING COMMAND CENTER</div><h1>مرکز فرمان</h1><p>تصمیم‌ها، ریسک، پوزیشن‌ها، بازار، گزارش‌ها و کنترل اضطراری در یک صفحه.</p></div><a class="btn secondary" href="/admin/command-center.php">بروزرسانی</a></div>
<?php if($notice!==''):?><div class="notice good"><?=cc_h($notice)?></div><?php endif?><?php if($error!==''):?><div class="notice bad"><?=cc_h($error)?></div><?php endif?>

<section class="hero-panel"><div class="page-eyebrow" style="color:#d8d4ff">LIVE CONTROL PLANE</div><h2><?=cc_h(strtoupper((string)$headline['bot_state']))?></h2><p>ارزش پرتفوی <?=cc_n($headline['portfolio_value_irt'],0)?> تومان • پوزیشن <?=$headline['active_positions']?>/<?=$headline['effective_max_positions']?></p><div class="hero-pills"><span class="hero-pill">BOT <?=cc_h($strip['bot'])?></span><span class="hero-pill">API <?=cc_h($strip['api'])?></span><span class="hero-pill">CIRCUIT <?=cc_h($strip['circuit'])?></span><span class="hero-pill">RISK <?=cc_h($strip['risk'])?></span><span class="hero-pill">EMERGENCY <?=cc_h($strip['emergency_mode'])?></span></div></section>

<div class="stat-grid"><div class="stat-card"><span>ارزش کل</span><b><?=cc_n($headline['portfolio_value_irt'],0)?></b><small>تومان</small></div><div class="stat-card"><span>PnL امروز</span><b class="<?=((float)$headline['today_net_pnl_irt']>=0)?'ok':'bad-text'?>"><?=cc_n($headline['today_net_pnl_irt'],0)?></b><small>تومان</small></div><div class="stat-card"><span>PnL ماه</span><b class="<?=((float)$headline['month_net_pnl_irt']>=0)?'ok':'bad-text'?>"><?=cc_n($headline['month_net_pnl_irt'],0)?></b><small>تومان</small></div><div class="stat-card"><span>Drawdown</span><b><?=cc_n($headline['current_drawdown_percent'],2)?>%</b></div><div class="stat-card"><span>پوزیشن</span><b><?=$headline['active_positions']?>/<?=$headline['effective_max_positions']?></b><small>سقف مؤثر</small></div></div>

<section class="panel <?=$strip['emergency_mode']!=='normal'?'cc-danger':''?>"><div class="panel-head"><div><h2>کنترل اضطراری</h2><p>Pause Buy فقط ورود را می‌بندد؛ Graceful Close پوزیشن‌ها را ترتیبی می‌بندد؛ Full Stop توقف کامل است.</p></div><span class="badge <?=cc_badge((string)$strip['emergency_mode'])?>"><?=cc_h($strip['emergency_mode'])?></span></div><div class="cc-actions"><?php foreach(['normal'=>'حالت عادی','pause_buys'=>'توقف خرید','graceful_close'=>'بستن تدریجی','full_stop'=>'توقف کامل'] as $mode=>$label):?><form method="post"><input type="hidden" name="csrf" value="<?=cc_h($_SESSION['csrf'])?>"><input type="hidden" name="action" value="emergency"><input type="hidden" name="mode" value="<?=$mode?>"><button class="btn <?=$mode==='full_stop'?'danger':($mode==='normal'?'primary':'secondary')?>" onclick="return confirm('حالت <?=$label?> اعمال شود؟')"><?=$label?></button></form><?php endforeach?></div></section>

<div class="panel-grid"><section class="panel"><div class="panel-head"><div><h2>چرا این تصمیم؟</h2><p>Explainability آخرین تصمیم موتور</p></div><span class="badge info"><?=cc_h((string)($decision['action']??'—'))?></span></div><h3><?=cc_h((string)($decision['symbol']??'بدون نماد'))?></h3><p><?=cc_h((string)($decision['reason_fa']??$decision['reason']??'—'))?></p><div class="metric-grid"><div class="metric"><span>Score</span><b><?=cc_h($decision['score']??'—')?></b></div><div class="metric"><span>Edge</span><b><?=cc_h($decision['tradable_edge_percent']??'—')?>%</b></div><div class="metric"><span>Spread</span><b><?=cc_h($decision['spread_percent']??'—')?>%</b></div><div class="metric"><span>Strategy</span><b><?=cc_h($decision['strategy']??'—')?></b></div></div></section><section class="panel"><div class="panel-head"><div><h2>هشدارهای فعال</h2><p>API، Pending، Circuit، Drawdown و سیستم</p></div><span class="badge <?=$alerts===[]?'good':'bad'?>"><?=count($alerts)?></span></div><?php if($alerts===[]):?><div class="notice good">هشدار مهمی فعال نیست.</div><?php else:?><?php foreach(array_slice($alerts,0,7) as $a):?><div class="cc-mini cc-alert <?=cc_h((string)$a['priority'])?>"><b><?=cc_h($a['title'])?></b><small><?=cc_h($a['body'])?></small></div><?php endforeach?><?php endif?></section></div>

<section class="panel"><div class="panel-head"><div><h2>پوزیشن‌های حرفه‌ای</h2><p>Entry / Mark / Net PnL / Fee / SL / TP / Holding</p></div><span class="badge info"><?=count($positions)?> ACTIVE</span></div><?php if($positions===[]):?><div class="empty">پوزیشن فعالی وجود ندارد.</div><?php else:?><?php foreach($positions as$p):?><div class="cc-position"><div><b><?=cc_h($p['symbol'])?></b><small><?=cc_h($p['status'])?> • <?=round((int)$p['holding_seconds']/60)?> دقیقه</small></div><div><small>Entry</small><b><?=cc_n($p['entry_price'],4)?></b></div><div><small>Mark</small><b><?=cc_n($p['mark_price'],4)?></b></div><div><small>Net PnL</small><b class="<?=((float)$p['unrealized_net_pnl_percent']>=0)?'ok':'bad-text'?>"><?=cc_n($p['unrealized_net_pnl_percent'],2)?>%</b></div><div><small>Fee</small><b><?=cc_n($p['total_estimated_fees_quote'],4)?></b></div><div><small>SL / TP</small><b><?=cc_n($p['stop_loss'],2)?> / <?=cc_n($p['take_profit'],2)?></b></div><div><small>Exit</small><b><?=cc_h($p['probable_exit_reason']??'—')?></b><a href="/api/trade-replay/<?=(int)$p['id']?>" target="_blank">Replay JSON</a></div></div><?php endforeach?><?php endif?></section>

<section class="panel"><div class="panel-head"><div><h2>Market Radar + Opportunity Ranking</h2><p>آخرین ارزیابی نمادهای دیده‌شده؛ امتیاز نمایش است و دستور خرید نیست.</p></div></div><div class="cc-radar"><?php foreach(['excellent'=>'Excellent','good'=>'Good','watch'=>'Watch','avoid'=>'Avoid'] as$cat=>$label):?><section class="<?=$cat==='good'?'goodradar':$cat?>"><b><?=$label?></b><?php $found=0;foreach($radar as$r)if($r['category']===$cat&&$found++<5):?><div class="cc-mini"><b><?=cc_h($r['symbol'])?></b><small>Edge <?=cc_n($r['edge_percent'],2)?>% • Score <?=cc_h($r['score'])?></small></div><?php endif;if($found===0):?><small>موردی نیست.</small><?php endif?></section><?php endforeach?></div><div class="table-wrap" style="margin-top:14px"><table><thead><tr><th>#</th><th>Symbol</th><th>Category</th><th>Action</th><th>Edge</th><th>Spread</th><th>Strategy</th></tr></thead><tbody><?php foreach($ranking as$i=>$r):?><tr><td><?=$i+1?></td><td><b><?=cc_h($r['symbol'])?></b></td><td><?=cc_h($r['category'])?></td><td><?=cc_h($r['action'])?></td><td><?=cc_n($r['edge_percent'],3)?>%</td><td><?=cc_n($r['spread_percent'],3)?>%</td><td><?=cc_h($r['strategy']??'—')?></td></tr><?php endforeach?></tbody></table></div></section>

<div class="panel-grid"><section class="panel"><div class="panel-head"><div><h2>عملکرد استراتژی</h2><p>Performance by Strategy</p></div></div><div class="table-wrap"><table><thead><tr><th>Strategy</th><th>Profile</th><th>Trades</th><th>Win</th><th>Avg</th></tr></thead><tbody><?php foreach(array_slice((array)$perf['by_strategy'],0,12)as$r):?><tr><td><?=cc_h($r['strategy_key']??'—')?></td><td><?=cc_h($r['profile_key']??'—')?></td><td><?=cc_h($r['trades']??0)?></td><td><?=cc_n(($r['win_rate']??$r['win_rate_percent']??0)*((float)($r['win_rate']??0)<=1?100:1),1)?>%</td><td><?=cc_n($r['average_return_percent']??0,3)?>%</td></tr><?php endforeach?></tbody></table></div></section><section class="panel"><div class="panel-head"><div><h2>عملکرد ارزها</h2><p>Performance by Coin</p></div></div><div class="table-wrap"><table><thead><tr><th>Asset</th><th>Trades</th><th>Win</th><th>Avg</th><th>Net PnL</th></tr></thead><tbody><?php foreach(array_slice((array)$perf['by_coin'],0,12)as$r):?><tr><td><b><?=cc_h($r['asset']??'—')?></b></td><td><?=cc_h($r['trades']??0)?></td><td><?=cc_n($r['win_rate_percent']??0,1)?>%</td><td><?=cc_n($r['average_return_percent']??0,3)?>%</td><td><?=cc_n($r['net_pnl']??0,2)?> <?=cc_h($r['display_unit']??'')?></td></tr><?php endforeach?></tbody></table></div></section></div>

<section class="panel"><div class="panel-head"><div><h2>Equity Curve</h2><p>۳۰ روز اخیر بر اساس PnL تحقق‌یافته</p></div></div><?php $curve=(array)$s['equity_curve'];$vals=array_map(static fn($x)=>(float)($x['cumulative_net_pnl']??0),$curve);$min=$vals?min($vals):0;$maxc=$vals?max($vals):0;$span=max(1,$maxc-$min);?><div class="cc-chart"><?php foreach($curve as$c):$h=10+90*(((float)($c['cumulative_net_pnl']??0)-$min)/$span);?><div class="cc-bar" style="height:<?=$h?>%" title="<?=cc_h($c['day']??'')?>: <?=cc_n($c['cumulative_net_pnl']??0,0)?>"></div><?php endforeach?></div></section>

<section class="panel"><div class="panel-head"><div><h2>Risk Heatmap</h2><p>همبستگی بازده نمونه‌های اخیر پوزیشن‌های فعال</p></div></div><div class="table-wrap"><table><thead><tr><th>Pair</th><th>Correlation</th><th>Risk</th></tr></thead><tbody><?php foreach(array_filter((array)$s['risk_heatmap']['cells'],static fn($c)=>($c['x']??'')<($c['y']??'')) as$c):?><tr><td><?=cc_h($c['x'])?> / <?=cc_h($c['y'])?></td><td><?=isset($c['correlation'])?cc_n($c['correlation'],3):'—'?></td><td><span class="badge <?=($c['risk']==='high')?'bad':(($c['risk']==='medium')?'info':'good')?>"><?=cc_h($c['risk'])?></span></td></tr><?php endforeach?></tbody></table></div></section>

<div class="panel-grid"><section class="panel"><div class="panel-head"><div><h2>Preset تنظیمات</h2><p>قبل از اعمال، تاریخچه Snapshot ذخیره می‌شود.</p></div></div><div class="cc-actions"><?php foreach($s['settings']['presets']as$key=>$p):?><form method="post"><input type="hidden" name="csrf" value="<?=cc_h($_SESSION['csrf'])?>"><input type="hidden" name="action" value="preset"><input type="hidden" name="preset" value="<?=cc_h($key)?>"><button class="btn secondary" onclick="return confirm('Preset <?=cc_h($p['label'])?> اعمال شود؟')"><?=cc_h($p['label'])?></button></form><?php endforeach?></div><div class="notice">Risk Index فعلی: <?=cc_n($s['settings']['risk_score']['score'],1)?> / 100 — <?=cc_h($s['settings']['risk_score']['level'])?></div></section><section class="panel"><div class="panel-head"><div><h2>Shadow / Paper Evaluation</h2><p>سیگنال‌ها بدون افزایش ریسک، ۱۵/۶۰/۲۴۰ دقیقه بعد ارزیابی می‌شوند.</p></div></div><div class="metric-grid"><div class="metric"><span>Samples</span><b><?=cc_h($shadow['samples']??0)?></b></div><div class="metric"><span>Avg 60m</span><b><?=cc_h($shadow['average_return_60m']??'—')?>%</b></div><div class="metric"><span>Positive 60m</span><b><?=cc_h($shadow['positive_60m_rate_percent']??'—')?>%</b></div></div><form method="post"><input type="hidden" name="csrf" value="<?=cc_h($_SESSION['csrf'])?>"><input type="hidden" name="action" value="shadow"><label><input type="checkbox" name="enabled" <?=$shadow['enabled']?'checked':''?>> فعال</label><button class="btn secondary">ذخیره</button></form></section></div>

<div class="panel-grid"><section class="panel"><div class="panel-head"><div><h2>Settings Preview</h2><p>پیش‌نمایش ریسک بدون ذخیره تغییرات</p></div></div><form method="post" class="field-grid"><input type="hidden" name="csrf" value="<?=cc_h($_SESSION['csrf'])?>"><input type="hidden" name="action" value="preview"><label class="field">سرمایه هر خرید<input name="position_percent" type="number" step=".1" value="<?=cc_h($s['settings']['current']['position_percent']??2)?>"></label><label class="field">سقف Exposure<input name="nobitex_portfolio_exposure_percent" type="number" step=".1" value="<?=cc_h($s['settings']['current']['nobitex_portfolio_exposure_percent']??35)?>"></label><label class="field">Max Position<input name="nobitex_max_positions" type="number" value="<?=cc_h($s['settings']['current']['nobitex_max_positions']??6)?>"></label><label class="field">Daily Loss<input name="daily_loss_limit_percent" type="number" step=".1" value="<?=cc_h($s['settings']['current']['daily_loss_limit_percent']??2)?>"></label><button class="btn secondary">محاسبه پیش‌نمایش</button></form><?php if(is_array($preview)):?><div class="notice">Risk: <?=cc_n($preview['risk_before']['score'],1)?> → <?=cc_n($preview['risk_after']['score'],1)?> (<?=cc_h($preview['impact'])?>)</div><?php endif?></section><section class="panel"><div class="panel-head"><div><h2>Strategy Lab</h2><p>What-if تاریخی؛ هیچ سفارش Live ارسال نمی‌شود.</p></div></div><form method="post" class="field-grid"><input type="hidden" name="csrf" value="<?=cc_h($_SESSION['csrf'])?>"><input type="hidden" name="action" value="lab"><label class="field">Position %<input name="position_percent" type="number" step=".1" value="<?=cc_h($s['settings']['current']['position_percent']??2)?>"></label><label class="field">Stop %<input name="stop_loss_percent" type="number" step=".1" value="<?=cc_h($s['settings']['current']['stop_loss_percent']??3)?>"></label><label class="field">Take %<input name="take_profit_percent" type="number" step=".1" value="<?=cc_h($s['settings']['current']['take_profit_percent']??5)?>"></label><button class="btn secondary">اجرای سناریو</button></form><?php if(is_array($lab)):?><div class="metric-grid"><div class="metric"><span>Samples</span><b><?=$lab['samples']?></b></div><div class="metric"><span>Win Rate</span><b><?=cc_n($lab['win_rate_percent'],1)?>%</b></div><div class="metric"><span>Avg</span><b><?=cc_n($lab['average_simulated_return_percent'],3)?>%</b></div><div class="metric"><span>Max DD</span><b><?=cc_n($lab['max_drawdown_percent'],2)?>%</b></div></div><small><?=cc_h($lab['note'])?></small><?php endif?></section></div>

<div class="panel-grid"><section class="panel"><div class="panel-head"><div><h2>Smart Notification Rules</h2><p>فیلتر تحویل هشدار به اپ</p></div></div><form method="post" class="field-grid"><input type="hidden" name="csrf" value="<?=cc_h($_SESSION['csrf'])?>"><input type="hidden" name="action" value="rules"><label class="field"><input type="checkbox" name="enabled" <?=$rules['enabled']?'checked':''?>> اعلان فعال</label><label class="field">حداقل Priority<select name="min_priority"><option>info</option><option>success</option><option <?=$rules['min_priority']==='warning'?'selected':''?>>warning</option><option <?=$rules['min_priority']==='critical'?'selected':''?>>critical</option></select></label><label class="field">Drawdown %<input name="drawdown_percent" type="number" step=".1" value="<?=cc_h($rules['drawdown_percent'])?>"></label><label class="field">Loss %<input name="pnl_loss_percent" type="number" step=".1" value="<?=cc_h($rules['pnl_loss_percent'])?>"></label><label><input type="checkbox" name="circuit_open" <?=$rules['circuit_open']?'checked':''?>> Circuit</label><label><input type="checkbox" name="api_failures" <?=$rules['api_failures']?'checked':''?>> API failures</label><label><input type="checkbox" name="pending_watchdog" <?=$rules['pending_watchdog']?'checked':''?>> Pending</label><button class="btn secondary">ذخیره قوانین</button></form></section><section class="panel"><div class="panel-head"><div><h2>گزارش روزانه / هفتگی</h2><p>خلاصه Fee-aware</p></div></div><div class="stat-grid"><div class="stat-card"><span>امروز</span><b><?=cc_n($s['reports']['daily']['net_pnl'],0)?></b></div><div class="stat-card"><span>هفته</span><b><?=cc_n($s['reports']['weekly']['net_pnl'],0)?></b></div><div class="stat-card"><span>ماه</span><b><?=cc_n($s['reports']['monthly']['net_pnl'],0)?></b></div><div class="stat-card"><span>Profit Factor</span><b><?=cc_n($s['reports']['profit_factor'],2)?></b></div></div></section></div>

<section class="panel"><div class="panel-head"><div><h2>Settings History + Rollback</h2><p>Snapshotهای اخیر تنظیمات</p></div></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Source</th><th>Label</th><th>Time</th><th>Risk profile</th><th>Action</th></tr></thead><tbody><?php foreach($history as$h):?><tr><td>#<?=(int)$h['id']?></td><td><?=cc_h($h['source'])?></td><td><?=cc_h($h['label'])?></td><td><?=cc_h($h['created_at'])?></td><td><?=cc_h($h['settings']['risk_profile']??'—')?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=cc_h($_SESSION['csrf'])?>"><input type="hidden" name="action" value="rollback"><input type="hidden" name="history_id" value="<?=(int)$h['id']?>"><button class="btn secondary" onclick="return confirm('تنظیمات به Snapshot #<?=(int)$h['id']?> برگردد؟')">Rollback</button></form></td></tr><?php endforeach?></tbody></table></div></section>

<section class="panel"><div class="panel-head"><div><h2>Activity Timeline</h2><p>رویدادها به زبان ساده</p></div></div><?php foreach(array_slice((array)$s['activity_timeline'],0,15)as$a):?><div class="cc-mini"><b><?=cc_h($a['text_fa']??'رویداد')?></b><small><?=cc_h($a['created_at_utc']??'')?> • <?=cc_h($a['source']??'')?></small></div><?php endforeach?></section>
<?php tradeAdminFooter($version);?></div></body></html>
