<?php

declare(strict_types=1);
function marketDataCleanupAssert(bool $condition,string $message):void{if(!$condition)throw new RuntimeException($message);}
$root=dirname(__DIR__);$repo=dirname($root);
foreach(['src/Exchange/BitpinClient.php','src/Trading/AutoTraderEngine.php','src/Trading/OrderService.php','src/Trading/MarketScanner.php']as$relative)marketDataCleanupAssert(!is_file($root.'/'.$relative),'Retired backend execution file still exists: '.$relative);
foreach(['TradeApp.kt','TradeAppV2.kt','TradeAppV3.kt']as$file)marketDataCleanupAssert(!is_file($repo.'/android/app/src/main/java/ir/trade/app/ui/'.$file),'Retired Android execution UI still exists: '.$file);
$marketHub=(string)file_get_contents($root.'/src/MarketData/MarketDataHub.php');$store=(string)file_get_contents($root.'/src/MarketData/MarketDataCredentialStore.php');$schema=(string)file_get_contents($root.'/src/Trading/Schema.php');$nobitexSchema=(string)file_get_contents($root.'/src/Trading/NobitexSchema.php');$controller=(string)file_get_contents($root.'/src/Trading/BotController.php');$api=(string)file_get_contents($root.'/public/index.php');$installer=(string)file_get_contents($root.'/public/install/index.php');$admin=(string)file_get_contents($root.'/public/admin/exchanges.php');$sql=(string)file_get_contents($root.'/database/schema.sql');$android=(string)file_get_contents($repo.'/android/app/src/main/java/ir/trade/app/data/TradeApi.kt');$entry=(string)file_get_contents($repo.'/android/app/src/main/java/ir/trade/app/ui/TradeEntry.kt');$v4=(string)file_get_contents($repo.'/android/app/src/main/java/ir/trade/app/ui/TradeAppV4.kt');
marketDataCleanupAssert(str_contains($marketHub,'api.bitpin.market/api/v1/mth/orderbook'),'Bitpin public order-book adapter must remain in MarketDataHub.');marketDataCleanupAssert(!str_contains($marketHub,'/usr/authenticate/')&&!str_contains($marketHub,'/odr/orders/'),'Bitpin market-data adapter must not expose private/execution endpoints.');
marketDataCleanupAssert(str_contains($store,"\$out['bitpin']")&&str_contains($store,"'role'=>'market_data_only'")&&str_contains($store,"'public_api'=>true"),'Bitpin must exist only as a public market-data source.');
foreach([$controller,$api,$nobitexSchema,$android,$entry,$v4]as$i=>$content)marketDataCleanupAssert(!str_contains(strtolower($content),'bitpin'),'Execution/runtime surface #'.$i.' still contains Bitpin legacy behavior.');marketDataCleanupAssert(!str_contains($api,'Trade\\Trading\\OrderService'),'Legacy OrderService import remains in public API.');marketDataCleanupAssert(!str_contains($android,'String="bitpin"')&&!str_contains($android,'String = "bitpin"'),'Android still defaults an execution request to Bitpin.');marketDataCleanupAssert(str_contains($entry,'TradeAppV4()'),'TradeEntry must point only to the current V4 UI.');
foreach(['bitpin_key','bitpin_secret','bitpin_live','bitpin_bot']as$needle)marketDataCleanupAssert(!str_contains($installer,$needle),'Installer still contains retired field: '.$needle);foreach(['autotrade_bitpin_enabled','live_trading_enabled']as$needle)marketDataCleanupAssert(!str_contains($nobitexSchema,$needle),'Nobitex schema still contains retired setting: '.$needle);
foreach(['autotrade_settings','autotrade_signals','autotrade_positions','autotrade_pnl','autotrade_events','bitpin_market_history_cache']as$table){marketDataCleanupAssert(!str_contains($sql,'CREATE TABLE IF NOT EXISTS '.$table.' '),'Fresh schema still creates retired table: '.$table);marketDataCleanupAssert(str_contains($schema,"'".$table."'")||str_contains($schema,'DROP TABLE IF EXISTS '.$table),'Upgrade cleanup does not drop retired table: '.$table);}
marketDataCleanupAssert(str_contains($schema,"DELETE FROM exchange_credentials WHERE exchange_name='bitpin'"),'Upgrade cleanup must remove old Bitpin credentials.');marketDataCleanupAssert(str_contains($schema,"DELETE FROM orders WHERE exchange_name='bitpin'"),'Upgrade cleanup must remove old Bitpin orders.');marketDataCleanupAssert(str_contains($schema,"LIKE '%bitpin%'"),'Upgrade cleanup must purge Bitpin-tagged execution history.');marketDataCleanupAssert(str_contains($schema,"unset(\$config['bitpin'])"),'Protected config cleanup must remove the old Bitpin config subtree.');marketDataCleanupAssert(str_contains($sql,'CREATE TABLE IF NOT EXISTS nobitex_autotrade_settings'),'Fresh schema must use the Nobitex-owned settings table.');
marketDataCleanupAssert(str_contains($admin,'<h2>Bitpin</h2>'),'Bitpin Market Data card is missing.');foreach(['Bitpin execution','قفل دائمی','Trading disabled','Live execution disabled']as$legacyLabel)marketDataCleanupAssert(!str_contains($admin,$legacyLabel),'Admin still frames Bitpin as a former execution venue: '.$legacyLabel);marketDataCleanupAssert(str_contains($admin,'Public Market Data فعال'),'Bitpin should be presented as an ordinary public market-data source.');
echo "Bitpin market-data-only destructive cleanup regression tests passed.\n";
