<?php

declare(strict_types=1);

require dirname(__DIR__, 3) . '/bootstrap.php';

use Trade\Config;
use Trade\Trading\BotController;

if (!Config::installed()) { header('Location: /install/'); exit; }
session_name('trade_admin');
session_set_cookie_params(['httponly'=>true,'secure'=>true,'samesite'=>'Strict','path'=>'/admin']);
session_start();
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
if (!isset($_SESSION['admin_id'])) { header('Location: /admin/'); exit; }
if (!isset($_SESSION['csrf'])) $_SESSION['csrf']=bin2hex(random_bytes(24));
function h(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}

$c=new BotController();$message='';$error='';$runResult=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
    $posted=(string)($_POST['csrf']??'');$session=(string)($_SESSION['csrf']??'');
    if($posted===''||$session===''||!hash_equals($session,$posted)){$_SESSION['csrf']=bin2hex(random_bytes(24));header('Location: /admin/bot/?csrf_refresh=1',true,303);exit;}
    try{
        $a=(string)($_POST['action']??'');$exchange=strtolower((string)($_POST['exchange']??'bitpin'));
        if($a==='exchange_bot'){$on=(string)($_POST['enabled']??'0')==='1';$c->setExchangeEnabled($exchange,$on);$message=($exchange==='nobitex'?'نوبیتکس':'بیت‌پین').' Bot '.($on?'فعال شد.':'غیرفعال شد.');}
        elseif($a==='exchange_live'){$on=(string)($_POST['enabled']??'0')==='1';$c->setExchangeLive($exchange,$on);$message=($exchange==='nobitex'?'نوبیتکس':'بیت‌پین').' Live '.($on?'فعال شد.':'غیرفعال شد.');}
        elseif($a==='kill_switch'){$on=(string)($_POST['enabled']??'1')==='1';$c->setKillSwitch($on);$message=$on?'توقف اضطراری سراسری فعال شد.':'توقف اضطراری برداشته شد.';}
        elseif($a==='save_settings'){$c->updateSettings($_POST);$message='تنظیمات مشترک ریسک و سیگنال ذخیره شد.';}
        elseif($a==='run_now'){$runResult=$c->runNow($exchange);$message='چرخه '.$exchange.' اجرا شد.';}
    }catch(Throwable $e){$error=mb_substr($e->getMessage(),0,700);}
}
if(isset($_GET['csrf_refresh']))$error='فرم قدیمی بود؛ صفحه تازه شد و هیچ تغییری انجام نشد.';
$status=$c->status();$data=$c->recentData(20);$settings=$status['settings'];$ex=$status['exchanges'];$csrf=h((string)$_SESSION['csrf']);
?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ربات‌های Trade</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f7fb;color:#172033;font-family:Tahoma,Arial,sans-serif}.wrap{max-width:1200px;margin:auto;padding:18px}.top,.row{display:flex;gap:9px;align-items:center;flex-wrap:wrap}.top{justify-content:space-between}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.card{background:#fff;border:1px solid #e1e7f0;border-radius:20px;padding:18px;margin-top:14px;box-shadow:0 8px 28px #14213a0b}.exchange{border-top:5px solid #1769ff}.badge{display:inline-block;padding:7px 10px;background:#f3f6fb;border-radius:999px;margin:3px}.ok{color:#087857}.bad{color:#b42318}.muted{color:#68748a;font-size:13px}.btn{border:0;border-radius:10px;padding:10px 13px;color:#fff;background:#1769ff;font-weight:700;cursor:pointer;text-decoration:none}.btn.gray{background:#657187}.btn.safe{background:#147a52}.btn.danger{background:#c62828}.btn.warn{background:#a86500}.msg,.err,.notice{padding:12px;border-radius:12px;margin-top:12px}.msg{background:#ecfff4;color:#176548}.err{background:#fff0f0;color:#a11}.notice{background:#fff6dd;color:#725000}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.metric{background:#f7f9fc;border-radius:13px;padding:12px}.metric b{display:block;font-size:18px;margin-top:5px}.fields{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.field label{display:block;font-size:12px;color:#68748a;margin-bottom:5px}input,select{width:100%;padding:10px;border:1px solid #ccd5e3;border-radius:9px;background:#fff}.scroll{overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:8px;border-bottom:1px solid #edf0f5;text-align:right;white-space:nowrap}.code{direction:ltr;text-align:left;white-space:pre-wrap;word-break:break-all;background:#101827;color:#eef5ff;padding:12px;border-radius:11px;font-family:monospace;font-size:12px}@media(max-width:760px){.wrap{padding:11px}.grid,.fields,.metrics{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}.btn{width:100%;text-align:center}.row form{width:100%}}
</style></head><body><div class="wrap">
<div class="top"><div><h1 style="margin:0 0 5px">ربات‌های معاملات خودکار GRAM</h1><div class="muted">Bitpin + Nobitex — کنترل مستقل هر صرافی</div></div><div class="row"><a class="btn gray" href="/admin/">پنل اصلی</a><a class="btn gray" href="/admin/exchanges.php">مدیریت صرافی‌ها</a></div></div>
<div class="notice"><b>LIVE:</b> هر صرافی دو کلید مستقل دارد: Bot و Live Execution. فقط وقتی هر دو روشن باشند و Kill Switch خاموش باشد، آن ربات اجازه ارسال سفارش واقعی دارد.</div>
<?php if($message):?><div class="msg"><?=h($message)?></div><?php endif?><?php if($error):?><div class="err"><?=h($error)?></div><?php endif?>
<?php if($runResult!==null):?><div class="card"><b>نتیجه اجرای دستی</b><div class="code"><?=h(json_encode($runResult,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?></div></div><?php endif?>
<div class="grid">
<?php foreach(['nobitex'=>'Nobitex','bitpin'=>'Bitpin'] as $key=>$name):$e=$ex[$key];$p=$e['performance'];?>
<div class="card exchange"><h2 style="margin-top:0"><?=$name?></h2><div><span class="badge">API <b class="<?=$e['credentials_configured']?'ok':'bad'?>"><?=$e['credentials_configured']?'READY':'NOT SET'?></b></span><span class="badge">Bot <b class="<?=$e['bot_enabled']?'ok':'bad'?>"><?=$e['bot_enabled']?'ON':'OFF'?></b></span><span class="badge">Live <b class="<?=$e['live_execution_enabled']?'ok':'bad'?>"><?=$e['live_execution_enabled']?'ON':'OFF'?></b></span></div>
<div class="row" style="margin-top:12px"><form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="exchange_bot"><input type="hidden" name="exchange" value="<?=$key?>"><input type="hidden" name="enabled" value="<?=$e['bot_enabled']?'0':'1'?>"><button class="btn <?=$e['bot_enabled']?'gray':'safe'?>"><?=$e['bot_enabled']?'خاموش کردن Bot':'روشن کردن Bot'?></button></form><form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="exchange_live"><input type="hidden" name="exchange" value="<?=$key?>"><input type="hidden" name="enabled" value="<?=$e['live_execution_enabled']?'0':'1'?>"><button class="btn <?=$e['live_execution_enabled']?'gray':'safe'?>"><?=$e['live_execution_enabled']?'خاموش کردن Live':'روشن کردن Live'?></button></form><form method="post" onsubmit="return confirm('چرخه LIVE برای <?=$name?> اجرا شود؟ ممکن است سفارش واقعی ایجاد شود.');"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="run_now"><input type="hidden" name="exchange" value="<?=$key?>"><button class="btn warn">اجرای یک چرخه</button></form></div>
<div class="metrics" style="margin-top:13px"><div class="metric">PnL امروز<b><?=h(number_format((float)$p['today_realized_pnl'],8,'.',''))?></b></div><div class="metric">PnL کل<b><?=h(number_format((float)$p['total_realized_pnl'],8,'.',''))?></b></div><div class="metric">Win Rate<b><?=h($p['win_rate_percent'])?>%</b></div></div>
<?php if($e['position']):?><p><b>پوزیشن فعال:</b> <?=h($e['position']['symbol'])?> — <?=h($e['position']['status'])?> — <?=h($e['position']['amount'])?></p><?php else:?><p class="muted">پوزیشن خودکار فعالی روی این صرافی وجود ندارد.</p><?php endif?>
</div><?php endforeach?>
</div>
<div class="card"><h2 style="margin-top:0">توقف اضطراری سراسری</h2><p class="<?=$status['kill_switch']?'bad':'ok'?>"><b><?=$status['kill_switch']?'فعال — هر دو صرافی متوقف هستند':'خاموش'?></b></p><form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="kill_switch"><input type="hidden" name="enabled" value="<?=$status['kill_switch']?'0':'1'?>"><button class="btn <?=$status['kill_switch']?'safe':'danger'?>"><?=$status['kill_switch']?'برداشتن توقف اضطراری':'توقف اضطراری هر دو صرافی'?></button></form></div>
<div class="card"><h2 style="margin-top:0">تنظیمات مشترک استراتژی و ریسک</h2><p class="muted">این تنظیمات برای هر دو ربات استفاده می‌شود؛ روشن/خاموش بودن هر صرافی مستقل است.</p><form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="save_settings"><div class="fields"><div class="field"><label>Quote Asset</label><select name="quote_asset"><option value="USDT" <?=$settings['quote_asset']==='USDT'?'selected':''?>>USDT</option><option value="IRT" <?=$settings['quote_asset']==='IRT'?'selected':''?>>IRT</option></select></div><div class="field"><label>Risk Profile</label><select name="risk_profile"><option value="safe" <?=$settings['risk_profile']==='safe'?'selected':''?>>Safe</option><option value="balanced" <?=$settings['risk_profile']==='balanced'?'selected':''?>>Balanced</option><option value="aggressive" <?=$settings['risk_profile']==='aggressive'?'selected':''?>>Aggressive</option></select></div><div class="field"><label>درصد سرمایه هر ورود</label><input type="number" step="0.1" min="0.5" max="20" name="position_percent" value="<?=h($settings['position_percent'])?>"></div><div class="field"><label>حداکثر مواجهه %</label><input type="number" step="0.1" min="1" max="25" name="max_position_percent" value="<?=h($settings['max_position_percent'])?>"></div><div class="field"><label>Stop Loss %</label><input type="number" step="0.1" min="0.5" max="15" name="stop_loss_percent" value="<?=h($settings['stop_loss_percent'])?>"></div><div class="field"><label>Take Profit %</label><input type="number" step="0.1" min="0.5" max="50" name="take_profit_percent" value="<?=h($settings['take_profit_percent'])?>"></div><div class="field"><label>زیان روزانه %</label><input type="number" step="0.1" min="1" max="15" name="daily_loss_limit_percent" value="<?=h($settings['daily_loss_limit_percent'])?>"></div><div class="field"><label>Minimum Signal Score</label><input type="number" min="35" max="90" name="min_signal_score" value="<?=h($settings['min_signal_score'])?>"></div><div class="field"><label>Cooldown دقیقه</label><input type="number" min="1" max="1440" name="cooldown_minutes" value="<?=h($settings['cooldown_minutes'])?>"></div></div><button class="btn" style="margin-top:12px">ذخیره تنظیمات</button></form></div>
<div class="grid"><?php foreach(['nobitex'=>'Nobitex','bitpin'=>'Bitpin'] as$key=>$name):?><div class="card"><h2 style="margin-top:0">سیگنال‌های <?=$name?></h2><div class="scroll"><table><tr><th>UTC</th><th>Market</th><th>Action</th><th>Score</th><th>Executed</th></tr><?php foreach($data[$key]['signals'] as$r):?><tr><td><?=h($r['created_at'])?></td><td><?=h($r['symbol'])?></td><td><?=h($r['action'])?></td><td><?=h($r['score'])?></td><td><?=((int)$r['executed']===1)?'بله':'خیر'?></td></tr><?php endforeach?></table></div></div><?php endforeach?></div>
<div class="card"><h2 style="margin-top:0">آخرین اجرای Cron</h2><div class="code"><?=h(json_encode($status['last_run'],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?></div></div>
</div></body></html>
