<?php

declare(strict_types=1);

require dirname(__DIR__, 3) . '/bootstrap.php';

use Trade\Config;
use Trade\Trading\BotController;

if (!Config::installed()) { header('Location: /install/'); exit; }
session_name('trade_admin');
session_set_cookie_params(['httponly'=>true,'secure'=>true,'samesite'=>'Strict','path'=>'/admin']);
session_start();
if (!isset($_SESSION['admin_id'])) { header('Location: /admin/'); exit; }
if (!isset($_SESSION['csrf'])) $_SESSION['csrf'] = bin2hex(random_bytes(24));
function h(mixed $v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }

$controller=new BotController(); $message=''; $error=''; $runResult=null;
if ($_SERVER['REQUEST_METHOD']==='POST') {
    if (!hash_equals((string)$_SESSION['csrf'],(string)($_POST['csrf']??''))) { http_response_code(403); exit('CSRF'); }
    try {
        $a=(string)($_POST['action']??'');
        if($a==='bot_enabled'){ $on=(string)($_POST['enabled']??'0')==='1'; $controller->setEnabled($on); $message=$on?'ربات معاملات خودکار فعال شد.':'ربات معاملات خودکار متوقف شد.'; }
        elseif($a==='live_enabled'){ $on=(string)($_POST['enabled']??'0')==='1'; $controller->setLiveEnabled($on); $message=$on?'ارسال سفارش واقعی فعال شد.':'ارسال سفارش واقعی غیرفعال شد.'; }
        elseif($a==='kill_switch'){ $on=(string)($_POST['enabled']??'1')==='1'; $controller->setKillSwitch($on); $message=$on?'توقف اضطراری فعال شد.':'توقف اضطراری برداشته شد.'; }
        elseif($a==='save_settings'){ $controller->updateSettings($_POST); $message='تنظیمات مدیریت ریسک و سیگنال ذخیره شد.'; }
        elseif($a==='run_now'){ $runResult=$controller->runNow(); $message='یک چرخه واقعی موتور معاملات اجرا شد.'; }
    } catch(Throwable $e){ $error=$e->getMessage(); }
}
$status=$controller->status(); $data=$controller->recentData(30); $settings=$status['settings']; $csrf=h((string)$_SESSION['csrf']);
?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ربات معاملات خودکار Trade</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f7fb;color:#172033;font-family:Tahoma,Arial,sans-serif}.wrap{max-width:1240px;margin:auto;padding:20px}.top{display:flex;justify-content:space-between;gap:12px;align-items:center}.top a{color:#1454aa;text-decoration:none}.badges,.actions{display:flex;flex-wrap:wrap;gap:8px}.badge{padding:8px 11px;border-radius:999px;background:#fff;border:1px solid #dfe6ef}.ok{color:#087857}.bad{color:#a11}.card{background:#fff;border:1px solid #e3e9f2;border-radius:18px;padding:18px;margin-top:14px;box-shadow:0 8px 28px #14213a0b}.hero{background:linear-gradient(135deg,#f7fbff,#eef4ff)}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.grid2{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.metric{border:1px solid #e5eaf2;border-radius:14px;padding:14px}.metric b{display:block;font-size:21px;margin-top:6px}.btn{border:0;border-radius:10px;padding:11px 14px;color:#fff;background:#1769ff;font-weight:700;cursor:pointer}.danger{background:#c62828}.safe{background:#16784a}.gray{background:#5e6a7d}.warn{background:#b36a00}.notice,.msg,.err{padding:12px 14px;border-radius:12px;margin-top:12px}.notice{background:#fff5df;border:1px solid #efd28b}.msg{background:#ecfff4;color:#176548}.err{background:#fff0f0;color:#a11}label{display:block;font-size:13px;margin-bottom:5px;color:#5f6c80}input,select{width:100%;padding:11px;border:1px solid #ccd5e3;border-radius:9px;background:#fff}.field{margin-bottom:12px}table{border-collapse:collapse;width:100%;font-size:12px}th,td{padding:9px;border-bottom:1px solid #edf0f5;text-align:right;white-space:nowrap}.scroll{overflow:auto}.mono{direction:ltr;text-align:left;font-family:monospace;white-space:pre-wrap;word-break:break-word;background:#f7f9fc;padding:10px;border-radius:10px}.muted{color:#6a768b;font-size:13px}@media(max-width:850px){.wrap{padding:12px}.top{align-items:flex-start;flex-direction:column}.grid,.grid2{grid-template-columns:1fr}}
</style></head><body><div class="wrap">
<div class="top"><div><h1 style="margin:0 0 5px">ربات معاملات خودکار GRAM</h1><div class="muted">Trade Production Auto-Trader — اجرای واقعی Bitpin</div></div><a href="/admin/">بازگشت به پنل اصلی</a></div>
<div class="badges" style="margin-top:12px"><span class="badge">دارایی: <b>GRAM</b> <span class="muted">(TON سابق)</span></span><span class="badge">ربات: <b class="<?=$status['bot_enabled']?'ok':'bad'?>"><?=$status['bot_enabled']?'فعال':'خاموش'?></b></span><span class="badge">اجرای واقعی: <b class="<?=$status['live_execution_enabled']?'ok':'bad'?>"><?=$status['live_execution_enabled']?'فعال':'خاموش'?></b></span><span class="badge">Kill Switch: <b class="<?=$status['kill_switch']?'bad':'ok'?>"><?=$status['kill_switch']?'فعال':'آزاد'?></b></span></div>
<div class="notice"><b>LIVE ONLY:</b> این مسیر هیچ معامله شبیه‌سازی‌شده‌ای انجام نمی‌دهد. وقتی ربات و اجرای واقعی فعال باشند و Kill Switch خاموش باشد، سیگنال معتبر می‌تواند مستقیماً سفارش واقعی Bitpin ایجاد کند.</div>
<?php if($message):?><div class="msg"><?=h($message)?></div><?php endif?><?php if($error):?><div class="err"><?=h($error)?></div><?php endif?>
<?php if($runResult!==null):?><div class="card"><b>نتیجه چرخه اجرا</b><div class="mono"><?=h(json_encode($runResult,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?></div></div><?php endif?>
<div class="card hero"><h2 style="margin-top:0">کنترل اجرای واقعی</h2><div class="actions">
<form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="bot_enabled"><input type="hidden" name="enabled" value="<?=$status['bot_enabled']?'0':'1'?>"><button class="btn <?=$status['bot_enabled']?'gray':'safe'?>"><?=$status['bot_enabled']?'توقف ربات':'فعال‌سازی ربات'?></button></form>
<form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="live_enabled"><input type="hidden" name="enabled" value="<?=$status['live_execution_enabled']?'0':'1'?>"><button class="btn <?=$status['live_execution_enabled']?'gray':'safe'?>"><?=$status['live_execution_enabled']?'قطع ارسال سفارش واقعی':'فعال‌سازی سفارش واقعی'?></button></form>
<form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="kill_switch"><input type="hidden" name="enabled" value="<?=$status['kill_switch']?'0':'1'?>"><button class="btn <?=$status['kill_switch']?'safe':'danger'?>"><?=$status['kill_switch']?'برداشتن توقف اضطراری':'توقف اضطراری'?></button></form>
<form method="post" onsubmit="return confirm('یک چرخه LIVE اجرا شود؟ در صورت وجود سیگنال معتبر ممکن است سفارش واقعی ثبت شود.');"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="run_now"><button class="btn warn">اجرای یک چرخه LIVE</button></form></div></div>
<div class="grid" style="margin-top:14px"><div class="metric">PnL امروز<b><?=h(number_format((float)$status['performance']['today_realized_pnl'],8,'.',''))?></b></div><div class="metric">PnL کل<b><?=h(number_format((float)$status['performance']['total_realized_pnl'],8,'.',''))?></b></div><div class="metric">Win Rate<b><?=h($status['performance']['win_rate_percent'])?>%</b></div></div>
<div class="grid2"><div class="card"><h2 style="margin-top:0">تنظیمات ریسک</h2><form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="action" value="save_settings">
<div class="field"><label>Quote Asset</label><input name="quote_asset" value="<?=h($settings['quote_asset'])?>" maxlength="12" required></div><div class="field"><label>پروفایل ریسک</label><select name="risk_profile"><option value="safe" <?=$settings['risk_profile']==='safe'?'selected':''?>>Safe</option><option value="balanced" <?=$settings['risk_profile']==='balanced'?'selected':''?>>Balanced</option><option value="aggressive" <?=$settings['risk_profile']==='aggressive'?'selected':''?>>Aggressive</option></select></div>
<div class="grid2"><div class="field"><label>درصد سرمایه هر ورود</label><input type="number" step="0.1" min="0.5" max="20" name="position_percent" value="<?=h($settings['position_percent'])?>"></div><div class="field"><label>حداکثر مواجهه GRAM %</label><input type="number" step="0.1" min="1" max="25" name="max_position_percent" value="<?=h($settings['max_position_percent'])?>"></div><div class="field"><label>Stop Loss %</label><input type="number" step="0.1" min="0.5" max="15" name="stop_loss_percent" value="<?=h($settings['stop_loss_percent'])?>"></div><div class="field"><label>Take Profit %</label><input type="number" step="0.1" min="0.5" max="50" name="take_profit_percent" value="<?=h($settings['take_profit_percent'])?>"></div><div class="field"><label>حداکثر زیان روزانه %</label><input type="number" step="0.1" min="1" max="15" name="daily_loss_limit_percent" value="<?=h($settings['daily_loss_limit_percent'])?>"></div><div class="field"><label>حداقل Signal Score</label><input type="number" min="35" max="90" name="min_signal_score" value="<?=h($settings['min_signal_score'])?>"></div><div class="field"><label>Cooldown (دقیقه)</label><input type="number" min="1" max="1440" name="cooldown_minutes" value="<?=h($settings['cooldown_minutes'])?>"></div></div><button class="btn">ذخیره تنظیمات</button></form></div>
<div class="card"><h2 style="margin-top:0">پوزیشن فعال</h2><?php if($status['position']):?><table><tr><th>وضعیت</th><td><?=h($status['position']['status'])?></td></tr><tr><th>بازار</th><td><?=h($status['position']['symbol'])?></td></tr><tr><th>مقدار</th><td><?=h($status['position']['amount'])?></td></tr><tr><th>ورود</th><td><?=h($status['position']['entry_price'])?></td></tr><tr><th>حد ضرر</th><td><?=h($status['position']['stop_loss'])?></td></tr><tr><th>حد سود</th><td><?=h($status['position']['take_profit'])?></td></tr></table><?php else:?><p class="muted">پوزیشن خودکار بازی وجود ندارد.</p><?php endif?><h3>آخرین اجرای Cron</h3><div class="mono"><?=h(json_encode($status['last_run'],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?></div><h3>Cron</h3><div class="mono">* * * * * /usr/local/bin/php /home/CPANEL_USER/path/to/Trade/cron/tick.php &gt;/dev/null 2&gt;&amp;1</div></div></div>
<div class="card"><h2 style="margin-top:0">سیگنال‌های اخیر</h2><div class="scroll"><table><tr><th>#</th><th>UTC</th><th>بازار</th><th>Action</th><th>Score</th><th>Price</th><th>Executed</th></tr><?php foreach($data['signals'] as$r):?><tr><td><?=h($r['id'])?></td><td><?=h($r['created_at'])?></td><td><?=h($r['symbol'])?></td><td><?=h($r['action'])?></td><td><?=h($r['score'])?></td><td><?=h($r['price'])?></td><td><?=((int)$r['executed']===1)?'بله':'خیر'?></td></tr><?php endforeach?></table></div></div>
<div class="card"><h2 style="margin-top:0">پوزیشن‌ها</h2><div class="scroll"><table><tr><th>#</th><th>بازار</th><th>وضعیت</th><th>مقدار</th><th>Entry</th><th>Exit</th><th>PnL</th><th>Opened</th><th>Closed</th></tr><?php foreach($data['positions'] as$r):?><tr><td><?=h($r['id'])?></td><td><?=h($r['symbol'])?></td><td><?=h($r['status'])?></td><td><?=h($r['amount'])?></td><td><?=h($r['entry_price'])?></td><td><?=h($r['exit_price'])?></td><td><?=h($r['realized_pnl'])?></td><td><?=h($r['opened_at'])?></td><td><?=h($r['closed_at'])?></td></tr><?php endforeach?></table></div></div>
<div class="card"><h2 style="margin-top:0">رویدادهای موتور</h2><div class="scroll"><table><tr><th>#</th><th>UTC</th><th>سطح</th><th>رویداد</th><th>جزئیات</th></tr><?php foreach($data['events'] as$r):?><tr><td><?=h($r['id'])?></td><td><?=h($r['created_at'])?></td><td><?=h($r['level'])?></td><td><?=h($r['event_name'])?></td><td><?=h(mb_substr((string)$r['context_json'],0,280))?></td></tr><?php endforeach?></table></div></div>
</div></body></html>
